@echo off
REM The following code was generated by ChatGPT-4o mini 

REM Check if the user provided the directory as an argument
if "%1"=="" (
    echo Usage: %0 directory_path
    exit /b
)

REM Set the directory to the one provided by the user
set dir=%1

REM Change to the directory where Router.py and config files are located
cd /d %dir%

REM Open a new command prompt for each router and display which router is being started
start cmd /k "echo Starting Router 0 with config-A.txt && python Router.py 0 7000 config-A.txt"
start cmd /k "echo Starting Router 1 with config-B.txt && python Router.py 1 7001 config-B.txt"
start cmd /k "echo Starting Router 2 with config-C.txt && python Router.py 2 7002 config-C.txt"
start cmd /k "echo Starting Router 3 with config-D.txt && python Router.py 3 7003 config-D.txt"
start cmd /k "echo Starting Router 4 with config-E.txt && python Router.py 4 7004 config-E.txt"
start cmd /k "echo Starting Router 5 with config-F.txt && python Router.py 5 7005 config-F.txt"
